name: Update README

on:
  pull_request:
    types:
      - closed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'       

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run Python script and capture output
        id: run-script
        run: |
          python src/main.py > out/script_output.txt
          echo "::set-output name=output::$(cat out/script_output.txt)"

      - name: Update README
        run: |
          echo "# My Updated README" >> README.md
          echo "${{ steps.run-script.outputs.output }}" >> README.md
          git commit -am "Update README after pull request merge"
          git push
